<?php
// Database connection using PostgreSQL
function getDBConnection() {
    $host = getenv('PGHOST');
    $port = getenv('PGPORT');
    $dbname = getenv('PGDATABASE');
    $user = getenv('PGUSER');
    $password = getenv('PGPASSWORD');
    
    try {
        $dsn = "pgsql:host=$host;port=$port;dbname=$dbname";
        $pdo = new PDO($dsn, $user, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
        return $pdo;
    } catch (PDOException $e) {
        error_log("Database connection failed: " . $e->getMessage());
        die("Database connection failed. Please try again later.");
    }
}

// Initialize database tables
function initializeDatabase() {
    $pdo = getDBConnection();
    
    // Users table
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            email VARCHAR(255) UNIQUE NOT NULL,
            password VARCHAR(255) NOT NULL,
            role VARCHAR(50) NOT NULL CHECK (role IN ('doctor', 'dentist', 'pharmacy', 'accountant', 'admin')),
            first_name VARCHAR(100) NOT NULL,
            last_name VARCHAR(100) NOT NULL,
            phone VARCHAR(20),
            address TEXT,
            business_name VARCHAR(255),
            license_number VARCHAR(100),
            specialty VARCHAR(100),
            is_verified BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ");
    
    // Accountant subscriptions
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS subscriptions (
            id SERIAL PRIMARY KEY,
            user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            status VARCHAR(50) DEFAULT 'inactive' CHECK (status IN ('active', 'inactive', 'cancelled')),
            plan_name VARCHAR(100) DEFAULT 'Professional',
            amount DECIMAL(10, 2) DEFAULT 80.00,
            start_date DATE,
            end_date DATE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ");
    
    // Accountant-Client relationships
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS accountant_clients (
            id SERIAL PRIMARY KEY,
            accountant_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            client_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'completed', 'cancelled')),
            year INTEGER NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(accountant_id, client_id, year)
        )
    ");
    
    // Documents table
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS documents (
            id SERIAL PRIMARY KEY,
            user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            filename VARCHAR(255) NOT NULL,
            original_name VARCHAR(255) NOT NULL,
            file_type VARCHAR(50) NOT NULL,
            file_size INTEGER NOT NULL,
            category VARCHAR(100) CHECK (category IN ('income', 'expense', 'invoice', 'tax_report', 'other')),
            year INTEGER NOT NULL,
            description TEXT,
            uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ");
    
    // Financial records
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS financial_records (
            id SERIAL PRIMARY KEY,
            user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            year INTEGER NOT NULL,
            total_income DECIMAL(15, 2) DEFAULT 0,
            total_expenses DECIMAL(15, 2) DEFAULT 0,
            estimated_profit DECIMAL(15, 2) DEFAULT 0,
            estimated_tax DECIMAL(15, 2) DEFAULT 0,
            tax_rate DECIMAL(5, 2) DEFAULT 25.00,
            notes TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, year)
        )
    ");
    
    // Commission tracking
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS commissions (
            id SERIAL PRIMARY KEY,
            accountant_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            client_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            amount DECIMAL(10, 2) NOT NULL,
            commission_rate DECIMAL(5, 2) DEFAULT 12.00,
            commission_amount DECIMAL(10, 2) NOT NULL,
            year INTEGER NOT NULL,
            status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled')),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ");
    
    // Tax reports (generated by accountants)
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS tax_reports (
            id SERIAL PRIMARY KEY,
            client_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            accountant_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            year INTEGER NOT NULL,
            status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft', 'pending_review', 'approved', 'submitted')),
            total_income DECIMAL(15, 2),
            total_deductions DECIMAL(15, 2),
            taxable_income DECIMAL(15, 2),
            tax_liability DECIMAL(15, 2),
            summary TEXT,
            report_file VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ");
    
    // Messages between users
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS messages (
            id SERIAL PRIMARY KEY,
            sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            receiver_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            subject VARCHAR(255),
            message TEXT NOT NULL,
            is_read BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ");
    
    return true;
}
?>
